[build]
  command = "bash ./netlify-build.sh"
  publish = "."

[context.production]
  command = "bash ./netlify-build.sh"

[context.deploy-preview]
  command = "bash ./netlify-build.sh"

[context.branch-deploy]
  command = "bash ./netlify-build.sh"

# Netlify Functions (αν έχεις)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# ΣΕΡΒΙΡΕ κανονικά το env.js (όχι rewrite)
[[redirects]]
  from = "/env.js"
  to = "/env.js"
  status = 200

# SPA fallback για τα υπόλοιπα
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
