[build]
  publish = "."

# Functions (αν έχεις Netlify functions)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Σέρβιρε το env.js κανονικά (όχι rewrite)
[[redirects]]
  from = "/env.js"
  to = "/env.js"
  status = 200

# SPA fallback ΜΟΝΟ για ό,τι δεν είναι static
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
